---
title: "Use regressors"
author: "Tourism Economics"
date: "February 12, 2016"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# require(directlabels)
# require(rmarkdown)
# require(gridExtra)
# require(gtable)
# require(Cairo)

library(arlodr)
library(xts, warn.conflicts=FALSE)
library(dplyr, warn.conflicts=FALSE)
library(tidyr, warn.conflicts=FALSE)
library(seasonal, warn.conflicts=FALSE)
require(xtable)
require(ggplot2)
require(knitr)
require(RColorBrewer)
require(scales)
library(lubridate)

# If I put autodep=TRUE as an argument in the following then I get
# some issues with the graphs, such as grey backgrounds and changes
# in labeling. Maybe it somehow impacts the theme?
#knitr::opts_chunk$set(cache=TRUE, cache.path='output_data/cache/', dpi=96)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, cache.path='../output_data/cache/', autodep=TRUE, fig.path='../output_data/figure_exp_seasonal_short/fig-',  fig.show='asis', fig.keep='high')
# tells it to keep going even if there is an error
knitr::opts_chunk$set(error = TRUE)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
load("~/Project/R projects/lodfor/output_data/ushist_m.Rdata")
load("~/Project/R projects/lodfor/output_data/ushist_q.Rdata")

```



```{r define_theme, echo=FALSE, message=FALSE, warning=FALSE}
#Displays palette and sets the ts1 theme

#display.brewer.pal(10, "RdBu")
mypallete <- brewer.pal( 10 , "RdBu" )
colors_ts1 <- scale_colour_manual(values = mypallete[c(10, 1, 5, 4)])
# I don't use the following, was an example I saw somewhere maybe as a way to 
# interpolate additional palette colors
#mypal <- colorRampPalette( brewer.pal( 10 , "RdBu" ) )
theme_ts1 <- function(base_size = 12, base_family = "") {
  theme_classic(base_size = base_size) %+replace%
    theme(                                 
      panel.grid.major.x=element_blank(),
      panel.grid.minor.x=element_blank(),
      panel.grid.minor.y=element_blank(),
      axis.ticks.y=element_line(size=.2),
      axis.ticks.x=element_line(size=.2),
      panel.background=element_blank(),
      legend.title=element_blank(),
      legend.key=element_rect(fill="white", colour = "white"),
      legend.key.size=unit(1, "cm"),
      legend.text=element_text(size=rel(1)),
      #legend.position = c(1, .1),
      legend.justification = "right",
      axis.line=element_line(size=.2),
      axis.title.y=element_blank(),
      axis.title.x=element_blank(),
      axis.text=element_text(color="black",size=rel(.7)),
      # following seems to adjust y-axis title
      plot.title=element_text(size=base_size * .8, face="plain",hjust=0,vjust=1)
    #theme(plot.title = element_text(lineheight=.8, face="bold"))
    )
}
theme_set(theme_ts1())
```

```{r}

segrun <- c("totus_demd")

```


### Set up data to run using: `r segrun`
```{r echo=FALSE, message=FALSE, warning=FALSE}

# shorten dates
#ushist_m_1 <- ushist_m["1987-01-01/2015-09-01"]

# sets up a single series to use for a few examples
demo_df <- ushist_m %>%
  data.frame(date=time(.), .) %>%
  select_("date", segrun)

```
  


```{r}
# try setting up several user regression variables as part of a holiday group

x <- demo_df %>%
  read.zoo(regular=TRUE, drop=FALSE) %>%
  xts() %>%
  convertIndex("yearmon")

temp_ser_ts <- as.ts(x, start = start(x), end = end(x))


# with more regressors
m3 <- seas(x = temp_ser_ts,
           regression.variables = c("tdnolpyear", "labor[3]", "easter[1]", "ls2001.Sep", "thank[3]"),
           forecast.maxlead = 30,# extends 30 quarters ahead
           seats.appendfcst="yes",
           xreg = cbind(vet1, chr1, jlf1), 
           regression.usertype = c("holiday", "holiday2", "holiday3"),
           regression.aictest = NULL)
#summary(m3)


# The basic model used by X-13ARIMA-SEATS for Easter and Labor Day effects assumes that the level of activity changes on the w−th day before the holiday for a specified w, and remains at the new level until the day before the holiday

# plot(m3)
# plot(final(m3))

# extract series
temp_sersa3 <- merge(
   # creates and merges invididual zoo series
   oa3 = as.zoo(original(m3)),
   sa3 = as.zoo(final(m3)),
   sa3_sf = as.zoo(series(m3, "s16"))) %>%
   # converts to xts
   as.xts(order.by = as.yearmon(index(.))) %>%
   data.frame(date=as.Date(time(.)), ., row.names=NULL)

```

