---
title: "load oef macro"
author: "Tourism Economics"
date: "Wednesday, October 15, 2014"
output: html_document
---

As an input, this expects a csv file. This csv file can be created using the
select file that I've set up and the OE macro model.
Also, I've modified it to pull FRED data using a quandl package.

```{r load_macro}
#sets up to later shorten data based on current date 
cur_year <- year(Sys.time())
end_year <- cur_year +15
end_year <- round(end_year,-1) -1
end_date <- paste(end_year,"-10-01",sep="")
```


```{r load_macro}
# require("stringr")
# require("dplyr")
# require("reshape2")
# require("zoo")
# require("xts")
# require("lubridate")
# require("ggplot2")

require("quantmod")

fname <- c("input_data/LODFOR_OEF_USMACRO_2015_02_13.csv")
temp <- read.csv(fname, header=TRUE, stringsAsFactors=FALSE)
# sets up column names
temp_names <- colnames(temp)
# removes periods in column names
temp_names <- gsub(".", "", temp_names, fixed = TRUE) 
# changes part of column names
temp_names <- tolower(temp_names)
temp_names <- gsub("xus", "us", temp_names) 
temp_names <- gsub("xca", "can", temp_names) 
temp_names <- gsub("xmx", "mex", temp_names) 

# replaces the existing column names
colnames(temp) <- temp_names

# works on the date column to get into a date format
# more difficult than I would have liked
hold <- temp[,1]
hold <- gsub("01$", " Q1", hold) 
hold <- gsub("02$", " Q2", hold) 
hold <- gsub("03$", " Q3", hold) 
hold <- gsub("04$", " Q4", hold) 
temp[,1] <- as.yearqtr(hold) 
head(temp)
temp$dates <- format(temp$dates, format="%Y Q%q")
temp$dates <- as.yearqtr(temp$dates)
# finally gets this to date format
temp$dates <- as.Date(temp$dates)
str(temp)

# much of the data is in character format
# this step converts to numeric and overwrites it
tempa <- temp[,2:ncol(temp)]
tempb <- data.matrix(tempa)
# could have also used sapply I believe
# tempb <- sapply(tempa, as.numeric )
temp[,2:ncol(temp)] <- tempb


#creates zoo object then xts object
temp1 <- read.zoo(temp)
class(temp1)
temp1 <- as.xts(temp1, frequency=4)
head(temp1)
oe_usmac_q <- temp1

# shortens data based on end date established at start of script
oe_usmac_q <- window(oe_usmac_q, end = end_date)
```

A few plots
```{r plots, echo=FALSE}

autoplot(oe_usmac_q$us_gdp)

autoplot(oe_usmac_q$us_up)
autoplot(oe_usmac_q$us_et)
autoplot(oe_usmac_q$us_rcorp)
autoplot(oe_usmac_q$us_pc)

temp <- (oe_usmac_q$us_gdp)
# percentage growth
tempdiff <- diff(temp)/lag(temp)
# annualized growth
tempcagr <- (temp/lag(temp))^4-1
#plotting annualized growth
autoplot(window(tempcagr, start=as.Date("2013-01-01"), end=as.Date("2015-01-01")))
tempa <- merge(temp, tempdiff, tempcagr)

# take a look at GDP growth rate as a check
a <- oe_usmac_q$us_gdp
# this is one way to calculate a CAGR on an xts object
a$us_gdp_cagr <- ((a$us_gdp/lag(a$us_gdp,1))^4-1)
window(a, start=as.Date("2013-01-01"), end=as.Date("2015-01-01"))
```

Load FRED data
```{r fred_data, echo=FALSE}
# new environment for data
data <- new.env()
# set dates
fredstart_date <- "1980-01-01"
# end is set up at start of script
fredend_date <- end_date

# set tickers
tickers <- c("FEDFUNDS", "GDPPOT", "USRECQ")

# import data from FRED database
getSymbols( tickers 
            ,src = "FRED"
            , env = data)


# based on 
# http://stackoverflow.com/questions/15980985/get-xts-objects-from-within-an-environment
# I looked at using gsa as follows, but it required another package qmao, that wasn't on Cran
data2 <- as.environment(eapply(data, "[", paste(fredstart_date, fredend_date, sep="/")))

#I should redo this, very clumsy
us_usrecq <- get("USRECQ", envir = data2)
us_usrecq <- as.data.frame(us_usrecq)
us_usrecq$date <- as.Date(row.names(us_usrecq))
us_usrecq <- us_usrecq %>%
  rename(us_usrecq = USRECQ)
us_usrecq <- us_usrecq %>%
  read.zoo(index.column = 2, drop=FALSE) %>%
  xts()

oe_usmac_q <- merge(oe_usmac_q, us_usrecq)
autoplot(oe_usmac_q$us_usrecq)
```

Cleans up
```{r clean}
rm(temp, temp1, tempa, fname, hold, temp_names)
```


Writing out files

```{r write_output}
# writes csv versions of the output files
write.zoo(oe_usmac_q, file="output_data/oe_usmac_q.csv", sep=",")
# saves Rdata versions of the output files
save(oe_usmac_q, file="output_data/oe_usmac_q.Rdata")
```

