---
title: "Untitled"
author: "Tourism Economics"
date: "March 15, 2016"
output: html_document
---

Here's one example from:
http://blog.rstudio.org/2015/09/29/purrr-0-1-0/


```{r setup, include=FALSE}

# just working through a couple purr examples

library(dplyr)
library(purrr)

random_group <- function(n, probs) {
  probs <- probs / sum(probs)
  g <- findInterval(seq(0, 1, length = n), c(0, cumsum(probs)),
                    rightmost.closed = TRUE)
  names(probs)[sample(g)]
}
partition <- function(df, n, probs) {
  n %>% 
    replicate(split(df, random_group(nrow(df), probs)), FALSE) %>%
    zip_n() %>%
    as_data_frame()
}

msd <- function(x, y) sqrt(mean((x - y) ^ 2))

# Genearte 100 random test-training splits, 
cv <- mtcars %>%
  partition(100, c(training = 0.8, test = 0.2)) %>% 
  mutate(
    # Fit the model
    model = map(training, ~ lm(mpg ~ wt, data = .)),
    # Make predictions on test data
    pred = map2(model, test, predict),
    # Calculate mean squared difference
    diff = map2(pred, test %>% map("mpg"), msd) %>% flatten()
  )

cv1 <- mtcars %>%
  partition(100, c(training = 0.8, test = 0.2)) %>% 
  mutate(
    # Fit the model
    model = map(training, ~ lm(mpg ~ wt, data = .)))

cv2 <- cv1 %>%
  # apply the predict function, with lists from the model and test columns as
  # arguments
  mutate(pred = map2(model, test, predict))

cv3 <- cv2 %>%
  # create the diff column, by running map2 which takes two arguments and applys
  # the msd function the two arguments are the pred column, and then the test
  # column fed into a step that uses the "mpg" as an extractor function to extract
  # the mpg item of the test list. (If you give map a character vector, it treats it
  # as an extractor function.)
  mutate(diff = map2(pred, test %>% map("mpg"), msd))

a <- cv3[1,"test"]


```


Here's another example from
https://medium.com/@erickramer/beautiful-data-science-with-functional-programming-and-r-a3f72059500b#.51g6rqnun

```{r}
library(Quandl)
library(purrr)
library(forecast)
library(dplyr)
datasets = c(Germany="FRED/DEURGDPR",
             Singapore="FRED/SGPRGDPR",
             Finland="FRED/FINRGDPR",
             France="FRED/FRARGDPR",
             Italy="FRED/ITARGDPR",
             Ireland="FRED/IRLRGDPR",
             Japan="FRED/JPNRGDPR",
             Netherlands="FRED/NLDRGDPR")

time_series = datasets %>%
  # for the list in datasets, apply the Quandl function to each one
  # with a type="ts" argument also
  map(Quandl, type="ts")


forecasts = time_series %>%
  # apply the auto.arima function to each time series
  map(auto.arima) %>%
  # I guess giving us a model for each, and then passing that to the 
  # forecast function, with argument h=10
  map(forecast, h=10)


par(mfrow=c(3,3)) # set grid for plots
# take each of the forecast objects, and the names of the forecast objects
# and pass them as arguments to a function that then uses them.
map2(forecasts, names(forecasts), 
     function(forecast, country) plot(forecast, 
                                      main=country, 
                                      bty="n",
                                      ylab="GDP",
                                      xlab="Year"))

```


```{r}
# based on the GDP example

library(Quandl)
library(purrr)
library(forecast)
library(dplyr)
datasets = c(Germany="FRED/DEURGDPR",
             Singapore="FRED/SGPRGDPR",
             Finland="FRED/FINRGDPR",
             France="FRED/FRARGDPR",
             Italy="FRED/ITARGDPR",
             Ireland="FRED/IRLRGDPR",
             Japan="FRED/JPNRGDPR",
             Netherlands="FRED/NLDRGDPR")

time_series = datasets %>%
  # for the list in datasets, apply the Quandl function to each one
  # with a type="ts" argument also
  map(Quandl, type="ts")

# put the list into the column of a data frame
df <- data_frame(time_series = time_series)

df_1 <- df %>%
  # apply the auto.arima function to each time series
  mutate(forecast_1 = map(time_series, auto.arima)) %>%
  # I guess giving us a model for each, and then passing that to the 
  # forecast function, with argument h=10
  mutate(forecast_2 = map(forecast_1, forecast, h=10))

```

