---
title: "US overview  slides"
author: "Tourism Economics"
date: "Sunday, October 12, 2014"
output:
  ioslides_presentation:
    fig_height: 5
    fig_width: 8.5
    smaller: yes
  beamer_presentation: default
  slidy_presentation: default
---

## Contents

- Bullet 1
- Bullet 2
- Bullet 3

```{r load_files, echo=FALSE, message=FALSE, warning=FALSE}
require(directlabels)
require(rmarkdown)
require(knitr)
require(RColorBrewer)
require(gridExtra)
require(gtable)
require(Cairo)

fpath <- c("~/Project/R projects/lodfor/")

# when kniting from the button, I either needed the full path or to add "../" in front of each
load(paste(fpath, "output_data/ushist_m.Rdata", sep=""))
load(paste(fpath, "output_data/outf_str_us_m.Rdata", sep=""))
load(paste(fpath, "output_data/ushist_q.Rdata", sep=""))
```

```{r readchunk, echo=FALSE, message=FALSE, warning=FALSE}
read_chunk('~/Project/R projects/lodfor/scripts/functions.R')
source('~/Project/R projects/lodfor/scripts/functions.R')
```

```{r first, echo=FALSE, message=FALSE, warning=FALSE}
# I forget what this does
<<variablesXY>>
```

```{r create_dataframes, echo=FALSE, message=FALSE, warning=FALSE}
# puts the monthly str data into a melted data frame
ushist_m_m <- ushist_m %>%
  window(end = as.Date("2014-12-01")) %>%
  data.frame(date=index(.),.) %>%
  melt(id.vars = c("date"))
# I used to have a version of ushist_m as a dataframe, but I'm not sure
# I need it, so I've stopped creating it and left ushist_m as an xts object

# puts the monthly simple forecast data into a melted data frame
outf_str_us_m_m <- outf_str_us_m %>%
  window(end = as.Date("2014-09-01")) %>%
  data.frame(date=index(.),.) %>%
  melt(id.vars = c("date"))

# puts the quarterly ushist into a melted data frame
ushist_q_m <- ushist_q %>%
window(end = as.Date("2017-10-01")) %>%
data.frame(date=index(.), .) %>%
melt(id.vars = c("date"))

# this is if I wanted to do things with a tidy format
ushist_q_tidy <- data.frame(date=time(ushist_q), ushist_q)%>%
  # select(-year,-month,-qtr,-days) %>%
  gather(segvar, value, -date, na.rm = FALSE) %>%
  # I had difficulty separating by the underscore
  # because there are more than one underscore in some
  # so my solution was to mutate the column, applying 
  # the sub function, which replaces the first occurance of
  # the underscore with a period
  mutate(segvar = sub("_",".", segvar)) %>%
  # then run the separate on the period, using backslashes
  # to escape out of the second character
  separate(segvar, c("seg", "variable"), sep = "\\.") 
```

```{r load_code_book_matrix, echo=FALSE, message=FALSE, warning=FALSE}
#Loads code_book_matrix and shows example contents
fname <- c(paste("~/Project/R projects/lodfor/input_data/code_book_matrix.csv", sep=""))
code_book_matrix <- read.csv(fname, stringsAsFactors=FALSE)
#head(code_book_matrix)
rm(fname)
```

```{r set_theme, echo=FALSE, message=FALSE, warning=FALSE}
#Displays palette and sets the ts1 theme

#display.brewer.pal(10, "RdBu")
mypallete <- brewer.pal( 10 , "RdBu" )
colors_ts1 <- scale_colour_manual(values = mypallete[c(10, 1, 5, 4)])
# I don't use the following, was an example I saw somewhere maybe as a way to 
# interpolate additional palette colors
#mypal <- colorRampPalette( brewer.pal( 10 , "RdBu" ) )
theme_ts1 <- function (base_size = 12, base_family = "") {
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(                                 
      panel.grid.major.x=element_blank(),
      panel.grid.minor.x=element_blank(),
      panel.grid.minor.y=element_blank(),
      axis.ticks.y=element_line(size=.2),
      axis.ticks.x=element_line(size=.2),
      panel.background=element_blank(),
      legend.title=element_blank(),
      legend.key=element_rect(fill="white", colour = "white"),
      legend.key.size=unit(1.5, "cm"),
      legend.text=element_text(size=rel(1.1)),
      legend.position = c(1, .1),
      legend.position = "none",
      legend.justification = "right",
      axis.line=element_line(size=.2),
      axis.title.y=element_blank(),
      axis.title.x=element_blank(),
      axis.text=element_text(color="black",size=rel(.9)),
      plot.title=element_text(size=base_size * .8, face="plain",hjust=0,vjust=1)
  #       theme(plot.title = element_text(lineheight=.8, face="bold"))
    )
}
theme_set(theme_ts1())
#this is also a useful theme to keep in mind
#theme_classic()
# this function gets the settings used by the current theme
#theme_get()
```

## Demand, monthly + GDP 
```{r demand_monthly_gdp, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
todo <- c("totus_demd_sa")
grtitle <- c("US room demand and GDP")
footnote <- c("Note: Room demand through December 2014 \nSource: STR, Tourism Economics")
starta <- as.Date("2004-01-01")
enda <- as.Date("2015-10-01")
index_year <- as.numeric(2006)
variable_text <- c(paste("Demand monthly, GDP quarterly,\nseasonally adjusted,\nindex ",index_year,"=100",sep=""))
variable_legend_1 <- c("Room demand")
variable_legend_2 <- c("GDP")

# filters and uses function to convert to index
temp <- ushist_m_m %>%
  filter(variable == todo, date >= starta, date <= enda) %>%
  index_m_melted(index_year=index_year)
temp2 <- ushist_q_m %>%
  filter(variable == "us_gdp", date >= starta, date <= enda) %>%
  index_q_melted(index_year=index_year)

p1 <- ggplot() +
  geom_line(data = temp, aes(x = date, y = value, color = variable), size = .6) + 
  geom_line(data = temp2, aes(x = date, y = value, color = variable), size = .9) +
  ggtitle(variable_text) +
  theme(legend.position=c(1, .2)) +
  scale_color_manual(values = c(mypallete[7:7], "grey40"), labels=c(variable_legend_1,variable_legend_2)) + 
  stat_smooth(data = temp, aes(x = date, y = value), method="loess", 
              color=mypallete[9:9], alpha=.4, span=.2, se = FALSE, fullrange=FALSE, size=.9, show_guide=FALSE)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)


# take a look at GDP growth rate as a check
#a <- ushist_q$us_gdp
#a$us_gdp_cagr <- ((a$us_gdp/lag(a$us_gdp,1))^4-1)
#window(a, start=as.Date("2013-01-01"), end=as.Date("2015-01-01"))
```

## Demand, ratio to population 
```{r demand_ratio_pop, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
#todo <- c("totus_demd_sa")
grtitle <- c("Room demand per capita")
footnote <- c("Source: STR; Census Bureau; Tourism Economics")
starta <- as.Date("1987-01-01")
enda <- as.Date("2014-10-01")
variable_text <- c("Annual room nights per capita \n(working age population)")
variable_legend_1 <- c("Room demand")

temp <- ushist_q_m %>% 
  filter(variable == "totus_demd_sa" | variable == "us_popw", date >= starta, date <= enda) %>%
  spread(variable, value) %>%
  mutate(dem_popw = totus_demd_sa * 365 / us_popw*1000) %>%
  select(date, dem_popw) %>%
  melt(id.vars = c("date"))

p1 <- ggplot() +
  geom_line(data = temp, aes(x = date, y = value, color = variable), size = .7) +
 ggtitle(variable_text) + 
scale_color_manual(values = c(mypallete[10:10], "grey70")) +
  stat_smooth(data = temp, aes(x = date, y = value), method=lm, fill = "grey90", color="grey40", alpha=.4, span=.7)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```

## Demand, ratio to employment 
```{r demand_ratio_emp, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
#todo <- c("totus_demd_sa")
grtitle <- c("Room demand as ratio to total employment")
footnote <- c("Source: STR; Bureau of Labor Statistics; Tourism Economics")
starta <- as.Date("1987-01-01")
enda <- as.Date("2014-10-01")
variable_text <- c("Annual room nights per employed person \n(household survey employment)")
variable_legend_1 <- c("Room demand")

temp <- ushist_q_m %>% 
  filter(variable == "totus_demd_sa" | variable == "us_et", date >= starta, date <= enda) %>%
  spread(variable, value) %>%
  mutate(dem_et = totus_demd_sa * 365 / us_et*1000) %>%
  select(date, dem_et) %>%
  melt(id.vars = c("date"))

p1 <- ggplot() +
  geom_line(data = temp, aes(x = date, y = value, color = variable), size = .7) +
 ggtitle(variable_text) + 
scale_color_manual(values = c(mypallete[10:10], "grey70")) +
  stat_smooth(data = temp, aes(x = date, y = value), method=lm, fill = "grey90", color="grey40", alpha=.4, span=.7)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```

## Occupancy labled
```{r occupancy_labled, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
todo <- c("totus_occ_sa")
grtitle <- c("Occupancy")

footnote <- c("Source: STR; Tourism Economics")
start_mean <- as.Date("2002-01-01") # for mean

start_xaxis <- as.Date("1995-01-01") # for x-axis
end_xaxis <- as.Date(max(temp$date)) # for x-axis
variable_text <- c("Seasonally adjusted, quarterly")
note <- paste("Average", year(start_mean), "to", year(end_xaxis), sep=" ")
#variable_legend_1 <- c("Text")

temp <- ushist_q_m %>% 
  filter(variable == todo, !is.na(value)) %>%
  group_by(variable) %>% 
  mutate(value_mean=mean(value)) %>%
  # gather is tidyr version of melt, creates measure and value columns, 
  # in a sense by gathering value to value_mean columns
  gather(measure, value, value:value_mean)
levels(temp$measure)[levels(temp$measure)=="value"] <- "Occupancy"
levels(temp$measure)[levels(temp$measure)=="value_mean"] <- "Average"

p1 <- ggplot(data = temp, aes(x = date, y=value, color = measure)) +
  geom_line(aes(group = measure)) + 
  coord_cartesian(xlim = c(start_xaxis, end_xaxis)) +
    ggtitle(variable_text) +
  scale_color_manual(values = c(mypallete[10:10], "grey70")) 
p1 <- direct.label (p1,
list ("lines2" , hjust = 0 , vjust = 1 , cex = 1 ))
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)

# direct.label(p,"lines2")
# direct.label(p,"first.qp")
# direct.label(p,"last.bumpup")
# direct.label(p,"last.qp", cex=2)
# direct.label(p,"maxvar.qp", cex=2)  
```


##Following graphs are based on code from around the STR presentation in November

## ADR, real long-term
```{r adr_real_lt, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
todo <- c("totus_adr_sarpc")
grtitle <- c("Real ADR, US")
footnote <- c("Source: STR; Bureau of Economic Analysis; Tourism Economics")
starta <- as.Date("1987-01-01")
enda <- as.Date("2015-01-01")
variable_text <- c("Seasonally adjusted")

temp <- ushist_q_m %>% 
  filter(date >= starta, date <= enda, variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date"))%>%
  mutate(group_date = cut(date, breaks = as.Date(c("1987-01-01", "1998-01-01","2015-01-01"))))

p1 <- ggplot(data = temp, aes(x = date, y = value, color = variable, shape = factor(group_date))) +
  geom_line(aes(x= date, y=value, group=1), size = .7) +
  ggtitle(variable_text) + 
  scale_color_manual(values = c(mypallete[10:10], "grey70")) +
  stat_smooth(method="lm", fill = "grey90", 
              color="grey40", span=.7, se = FALSE)+ 
  scale_y_continuous(labels = dollar)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```


## ADR, real medium-term
```{r adr_real_mt, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
todo <- c("totus_adr_sarpc")
grtitle <- c("Real ADR, US")
footnote <- c("Source: STR; Bureau of Economic Analysis; Tourism Economics")
starta <- as.Date("2001-01-01")
enda <- as.Date("2014-01-01")
variable_text <- c("Seasonally adjusted")

temp <- ushist_q_m %>% 
  filter(date >= starta, date <= enda, variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date"))

p1 <- ggplot() +
  geom_line(data = temp, aes(x = date, y = value, color = variable), size = .7) +
 ggtitle(variable_text) + 
scale_color_manual(values = c(mypallete[10:10], "grey70")) + 
  scale_y_continuous(labels = dollar)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```

## ADR, real short-term
```{r adr_real_st, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
todo <- c("totus_adr_sarpc")
grtitle <- c("Real ADR, US")
footnote <- c("Source: STR; Bureau of Economic Analysis; Tourism Economics")
starta <- as.Date("2006-01-01")
enda <- as.Date("2015-01-01")
variable_text <- c("Seasonally adjusted")

temp <- ushist_q_m %>% 
  filter(date >= starta, date <= enda, variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date")) %>%
  mutate(group_date = cut(date, breaks = as.Date(c("2004-01-01", "2008-04-01", "2010-01-01","2015-01-01"))))

p1 <- ggplot(data = temp, aes(x = date, y = value, shape = factor(group_date))) + 
 geom_line(aes(x= date, y=value, group=1), size = .7, color=mypallete[10:10]) +
 ggtitle(variable_text) + 
 scale_color_manual(values = c(mypallete[10:10], "grey70"))  + 
 stat_smooth(method="lm", fill = "grey70", 
             color="grey40", alpha=.4, span=.8, se = FALSE)+ 
  scale_y_continuous(labels = dollar)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```

## ADR, short-term
```{r adr_st, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
todo <- c("totus_adr_sa")
grtitle <- c("ADR, US")
footnote <- c("Source: STR; Bureau of Economic Analysis; Tourism Economics")
starta <- as.Date("2006-01-01")
enda <- as.Date("2015-01-01")
variable_text <- c("Seasonally adjusted")

temp <- ushist_q_m %>% 
  filter(date >= starta, date <= enda, variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date")) %>%
  mutate(group_date = cut(date, breaks = as.Date(c("2004-01-01", "2008-04-01", "2010-01-01","2015-01-01"))))

p1 <- ggplot(data = temp, aes(x = date, y = value, shape = factor(group_date))) + 
 geom_line(aes(x= date, y=value, group=1), size = .7, color=mypallete[10:10]) +
 ggtitle(variable_text) + 
 scale_color_manual(values = c(mypallete[10:10], "grey70"))  + 
 stat_smooth(method="lm", fill = "grey70", 
             color="grey40", alpha=.4, span=.8, se = FALSE)+ 
  scale_y_continuous(labels = dollar)
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)
```



## ADR, growth, short-term 
```{r adr_gr_st, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
 
todo <- c("totus_adr_sa")
grtitle <- c("ADR, US")
footnote <- c("Source: STR; Tourism Economics")
 
# starta <- as.Date("2008-01-01")
# enda <- as.Date("2015-01-01")
variable_text <- c("Seasonally adjusted")
 
temp <- ushist_q_m %>% 
  filter(variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date")) %>%
  select(-variable) %>%
  mutate(group_date = cut(date, breaks = as.Date(c("2004-01-01", "2008-01-01", "2009-10-01","2015-01-01")))) %>%
  mutate(cagr = (value / lag(value))^4 -1, pchya = (value/lag(value, 4)) -1) %>%
  select(-value) %>%
 # filter(date >= starta, date <= enda) %>%
  melt(id.vars = c("date", "group_date")) %>%
  transform(value = as.numeric(value))

start_xaxis <- as.Date("2008-01-01") # for x-axis
end_xaxis <- as.Date("2015-01-01") # for x-axis
p1 <- ggplot(data = temp, aes(x = date, y = value, group=variable)) + 
 geom_line(size = .7, color=mypallete[10:10]) +
  geom_point() +
 ggtitle(variable_text) + 
 scale_color_manual(values = c(mypallete[10:10], "grey70"))  + 
 stat_smooth(method="loess", fill = "grey70", 
             color="grey40", alpha=.4, span=.8, se = TRUE) +
 scale_y_continuous(labels = percent)  + 
    coord_cartesian(xlim = c(start_xaxis, end_xaxis)) +
 facet_wrap(~ variable, ncol=1, scales = "free")+
# doesn't add minor tick marks, just for grid I guess 
 scale_x_date(labels = date_format("%Y"), breaks = "1 year", minor_breaks = "3 months") 
# useful
#http://stackoverflow.com/questions/10151123/how-to-specify-columns-in-facet-grid-or-how-to-change-labels-in-facet-wrap
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)

```


## ADR, growth cagr, short-term 
```{r adr_gr_cagr_st, echo=FALSE, message=FALSE, warning=FALSE, dev='CairoPNG'}
#sets variable and text items
 
todo <- c("totus_adr_sa")
grtitle <- c("ADR, US")
footnote <- c("Source: STR; Tourism Economics")
variable_text <- c("Seasonally adjusted, compound annual growth rate")
 
temp <- ushist_q_m %>% 
  filter(variable == todo) %>%
  spread(variable, value) %>%
  melt(id.vars = c("date")) %>%
  select(-variable) %>%
#  mutate(group_date = cut(date, breaks = as.Date(c("2004-01-01", "2008-01-01", "2009-10-01","2015-01-01")))) %>%
  mutate(cagr = (value / lag(value))^4 -1) %>%
  select(-value) %>%
 # filter(date >= starta, date <= enda) %>%
  melt(id.vars = c("date")) %>%
  transform(value = as.numeric(value))

start_xaxis <- as.Date("2003-01-01") # for x-axis
end_xaxis <- as.Date("2015-01-01") # for x-axis
p1 <- ggplot(data = temp, aes(x = date, y = value, group=variable)) + 
 geom_line(size = .7, color=mypallete[10:10]) +
  geom_point() +
 ggtitle(variable_text) + 
 scale_color_manual(values = c(mypallete[10:10], "grey70"))  + 
 stat_smooth(method="loess", fill = "grey70", 
             color="grey40", alpha=.4, span=.25, se = TRUE) +
 scale_y_continuous(labels = percent)  + 
    coord_cartesian(xlim = c(start_xaxis, end_xaxis), ylim = c(-.1,.1)) +
# facet_wrap(~ variable, ncol=1, scales = "free")+
# doesn't add minor tick marks, just for grid I guess 
 scale_x_date(labels = date_format("%Y"), breaks = "1 year", minor_breaks = "3 months") 
# useful
#http://stackoverflow.com/questions/10151123/how-to-specify-columns-in-facet-grid-or-how-to-change-labels-in-facet-wrap
plot_title_1(plot=p1, grtitle=grtitle, footnote=footnote)

```
