---
title: "US overview  slides"
author: "Tourism Economics"
date: "Sunday, October 12, 2014"
output:
  ioslides_presentation:
    fig_height: 5.5
    fig_width: 8.5
    smaller: yes
  slidy_presentation: default
---

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output

```{r}
load("~/Project/R projects/lodfor/output_data/out_str_q_us.Rdata")

require(zoo)
require(xts)
require(dplyr)
require(reshape2)
require(ggplot2)
require(RColorBrewer)
require(gridExtra)
require(gtable)

xts1 <- out_str_q_us
xts1 <- window(xts1, end = as.Date("2014-08-01"))
df1 <- data.frame(time=time(xts1), xts1)
df2 <- df1
df2m <- melt(df2, id.vars = c("time"))
df2m[1:4,]
```

Loads code_book_matrix and shows example contents
```{r load_code_book_matrix,echo=FALSE}
fname <- c("~/Project/R projects/lodfor/input_data/code_book_matrix.csv")
code_book_matrix <- read.csv(fname, stringsAsFactors=FALSE)
head(code_book_matrix)
```

Displays palette and sets the ts1 theme

```{r set_theme, echo=FALSE}
#display.brewer.pal(10, "RdBu")
mypallete <- brewer.pal( 10 , "RdBu" )
colors_ts1 <- scale_colour_manual(values = mypallete[c(10, 1, 5, 4)])
# I don't use the following, was an example I saw somewhere maybe as a way to 
# interpolate additional palette colors
#mypal <- colorRampPalette( brewer.pal( 10 , "RdBu" ) )

theme_ts1 <- function (base_size = 12, base_family = "") {
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(                                  #text=element_text(family="Lato Light", size=14),
      panel.grid.major.x=element_blank(),
      panel.grid.minor.x=element_blank(),
      panel.grid.minor.y=element_blank(),
     # panel.grid.major.y=element_line(colour="#ECECEC", size=2, linetype=1),
      axis.ticks.y=element_line(size=.2),
      panel.background=element_blank(),
      legend.title=element_blank(),
      legend.key=element_rect(fill="white", colour = "white"),
      #legend.key.size=unit(1.5, "cm"),
      legend.text=element_text(size=rel(1.1)),
      legend.position = c(1, .1),
      #legend.position = "top",
      legend.justification = "right",
      #axis.title.y=element_text(angle=0),
      axis.line=element_line(size=.2),
      axis.title.y=element_blank(),
      axis.title.x=element_blank(),
      axis.text=element_text(color="black",size=rel(.9)),
      plot.title=element_text(size=base_size * 1, face="plain",hjust=0,vjust=1)
    )
}
theme_set(theme_ts1())
#this is also a useful theme to keep in mind
#theme_classic()
# this function gets the settings used by the current theme
#theme_get()
```


## Slide with Plot
```{r room_demand_plot, echo=FALSE, warning=FALSE}
#sets variable and text items
todo <- c("totus_demd_sa")
grtitle <- c("Room demand")
footnote <- c("Source: Smith Travel Research, Tourism Economics")

# filters data frame and loads variable text based on code_book_matrix
temp <- filter(df2m,variable == todo)
variable_text <- code_book_matrix[code_book_matrix$variable_name == 
                                    c("totus_demd_sa"), "variable_text"]
# creates plot
p1 <- ggplot(temp, aes(x = time, y = value, color = variable)) +
  geom_line(size = .9) +
  #scale_color_manual(values = c(mypallete[8:8], "grey80"), 
  #                 labels=c(variable_text, "test")) +
  scale_color_manual(values = c(mypallete[8:8], "grey80")) +
  ggtitle(variable_text) + 
  theme(legend.position="none") #turns off legend
p1 <- p1 + stat_smooth(method = "lm")
# adds the title
grobframe <- arrangeGrob(p1, ncol=1, nrow=1,
                         main = textGrob(grtitle, x=0, hjust=0, vjust=0.4, 
                                         gp = gpar(fontsize=16, fontface="bold")),
                         sub = textGrob(footnote, x=0, hjust=0, vjust=0.1, 
                                        gp = gpar(fontface="italic", fontsize=8)))
grid.newpage()
grid.draw(grobframe)
```


